<?php
declare(strict_types=1);

// FreeIp SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

FreeIpUtility::setRegistrar(function (FreeIpUtility $u): void {
    $u->clean = [FreeIpClean::class, 'call'];
    $u->done = [FreeIpDone::class, 'call'];
    $u->make_error = [FreeIpMakeError::class, 'call'];
    $u->feature_add = [FreeIpFeatureAdd::class, 'call'];
    $u->feature_hook = [FreeIpFeatureHook::class, 'call'];
    $u->feature_init = [FreeIpFeatureInit::class, 'call'];
    $u->fetcher = [FreeIpFetcher::class, 'call'];
    $u->make_fetch_def = [FreeIpMakeFetchDef::class, 'call'];
    $u->make_context = [FreeIpMakeContext::class, 'call'];
    $u->make_options = [FreeIpMakeOptions::class, 'call'];
    $u->make_request = [FreeIpMakeRequest::class, 'call'];
    $u->make_response = [FreeIpMakeResponse::class, 'call'];
    $u->make_result = [FreeIpMakeResult::class, 'call'];
    $u->make_point = [FreeIpMakePoint::class, 'call'];
    $u->make_spec = [FreeIpMakeSpec::class, 'call'];
    $u->make_url = [FreeIpMakeUrl::class, 'call'];
    $u->param = [FreeIpParam::class, 'call'];
    $u->prepare_auth = [FreeIpPrepareAuth::class, 'call'];
    $u->prepare_body = [FreeIpPrepareBody::class, 'call'];
    $u->prepare_headers = [FreeIpPrepareHeaders::class, 'call'];
    $u->prepare_method = [FreeIpPrepareMethod::class, 'call'];
    $u->prepare_params = [FreeIpPrepareParams::class, 'call'];
    $u->prepare_path = [FreeIpPreparePath::class, 'call'];
    $u->prepare_query = [FreeIpPrepareQuery::class, 'call'];
    $u->graphql_body = [FreeIpGraphql::class, 'body'];
    $u->graphql_errors = [FreeIpGraphql::class, 'errors'];
    $u->result_basic = [FreeIpResultBasic::class, 'call'];
    $u->result_body = [FreeIpResultBody::class, 'call'];
    $u->result_headers = [FreeIpResultHeaders::class, 'call'];
    $u->transform_request = [FreeIpTransformRequest::class, 'call'];
    $u->transform_response = [FreeIpTransformResponse::class, 'call'];
});
