-- Typed models for the FreeIp SDK (LuaLS annotations).
--
-- GENERATED from the API model: main.kit.entity.<e>.fields[] and per-op
-- params (op.<name>.points[].args.params[]). Field/param types come from the
-- canonical type sentinels via @voxgig/sdkgen canonToType (source of truth:
-- @voxgig/apidef VALID_CANON). Annotations only — no runtime effect. Do not
-- edit by hand.

---@class IpGeolocation

---@class IpGeolocationLoadMatch
---@field ip_address? string

---@class Json
---@field asn? string
---@field asnOrganization? string
---@field capital? string
---@field cityName? string
---@field code? string
---@field continent? string
---@field continentCode? string
---@field countryCode? string
---@field countryName? string
---@field currencies? table
---@field currency? table
---@field ip? string
---@field ipAddress? string
---@field ipVersion? number
---@field isProxy? boolean
---@field language? string
---@field languages? table
---@field latitude? number
---@field longitude? number
---@field name? string
---@field phoneCodes? table
---@field regionCode? string
---@field regionName? string
---@field timeZone? string
---@field timeZones? table
---@field tlds? table
---@field zipCode? string

---@class JsonLoadMatch
---@field id string

---@class JsonListMatch
---@field asn? string
---@field asnOrganization? string
---@field capital? string
---@field cityName? string
---@field code? string
---@field continent? string
---@field continentCode? string
---@field countryCode? string
---@field countryName? string
---@field currencies? table
---@field currency? table
---@field ip? string
---@field ipAddress? string
---@field ipVersion? number
---@field isProxy? boolean
---@field language? string
---@field languages? table
---@field latitude? number
---@field longitude? number
---@field name? string
---@field phoneCodes? table
---@field regionCode? string
---@field regionName? string
---@field timeZone? string
---@field timeZones? table
---@field tlds? table
---@field zipCode? string

---@class JsonCreateData
---@field asn? string
---@field asnOrganization? string
---@field capital? string
---@field cityName? string
---@field code? string
---@field continent? string
---@field continentCode? string
---@field countryCode? string
---@field countryName? string
---@field currencies? table
---@field currency? table
---@field ip? string
---@field ipAddress? string
---@field ipVersion? number
---@field isProxy? boolean
---@field language? string
---@field languages? table
---@field latitude? number
---@field longitude? number
---@field name? string
---@field phoneCodes? table
---@field regionCode? string
---@field regionName? string
---@field timeZone? string
---@field timeZones? table
---@field tlds? table
---@field zipCode? string

local M = {}

return M
